// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-variants/BoldVibrant.tsx": () => import("../components/mockups/chat-variants/BoldVibrant.tsx"),
  "./components/mockups/chat-variants/DarkGlass.tsx": () => import("../components/mockups/chat-variants/DarkGlass.tsx"),
  "./components/mockups/chat-variants/SoftClinical.tsx": () => import("../components/mockups/chat-variants/SoftClinical.tsx")
};
